name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - run: yarn install

      - run: yarn lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - run: yarn install

      - run: yarn build

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - run: yarn install

      - run: yarn test --coverage

      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage/clover.xml
          fail_ci_if_error: true
